version: '3.4'

services:
  deepdream:
    image: deepdream
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true  
    tty: true       
